### ISSUE TITLE
Rename `dagger-action` to something less confusing

### ISSUE THREAD

**Issue by shykes** [dagger/dagger-for-github#21]
## Problem

From the point of view of a Github Actions user, "dagger-action" makes perfect sense. But from the point of view of the Dagger community, it is confusing: is it a product called "action" by Dagger? Is it a way to perform an action in Dagger? Is it a clone of Github Actions by Dagger?

## Solution

After discussion: the most pragmatic solution seems to be renaming this repo to `dagger-for-github`.

## Alternative options

The following options were discussed:

> 1. Borrowing from Docker's edition model: `dagger-for-github`
> 2. Another variation on the edition model: `dagger-on-github`
> 3. Minimalist variatin: `dagger-github`
> 4. Same idea but more specific: `dagger-gha`
> 
> My preference right now is option 1: `dagger-for-github`. Simply because the format of "Docker for Mac", "Github for Mac" (fun fact: this is the inspiration for D4M :) is familiar to many developers.

**Comment by shykes** [comment]
cc @grouville @crazy-max

**Comment by crazy-max** [comment]
`dagger-ghaction`?

**Comment by grouville** [comment]
> WDYT?

You're totally right. This action provides a way to use dagger in combination with GitHub.

I like the edition model: simple, known and to-the-point. Even though I agree that it sounds a little bit longer than: `Docker for Mac` (4 syllabus), the benefits far outweigh this little inconvenience

I checked and Vercel follows the same model, let's not reinvent the wheel:
* Vercel for Github -> Dagger for Github
* Vercel for Gitlab -> Dagger for Gitlab
* Vercel for Bitbucket -> Dagger for Bitbucket
* Any platform -> Dagger for xxx

**Comment by grouville** [comment]
> `dagger-ghaction`?

It totally fits for this use case, but I'm having a hard time seing how we would port this model with Gitlab and Bitbucket terminology?

**Comment by shykes** [comment]
Let's go with `dagger-for-github`. I updated the top comment. What work needs to be done besides renaming the github repo? @grouville can you track this and let me know when we are clear to rename?

cc @aluzzardi who owns project infra.

**Comment by grouville** [comment]
After talking with @crazy-max, the renaming part needs to be done by him (more complex than it seems, need Github team interaction). You can assign this issue to him. I will take care of the DX redesign (issue #21)
