### ISSUE TITLE
Update to use `dagger-cue` when released

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger-for-github#75]

**Comment by fire** [comment]
dagger-cue has been released and all previous github actions broke for example `dagger do build`

**Comment by shykes** [comment]
Flagging this one as high priority... I know there are workarounds that allow current dagger-cue users to continue using the action, but I believe *they cannot upgrade it*. We should prioritize the work discussed, of modifying the github app so that it can run either `dagger` or `dagger-cue`.

**Comment by jpadams** [comment]
> Flagging this one as high priority... I know there are workarounds that allow current dagger-cue users to continue using the action, but I believe _they cannot upgrade it_. We should prioritize the work discussed, of modifying the github ~app~ _action_ so that it can run either `dagger` or `dagger-cue`.

@shykes I've been digging into this. A PR from @marcosnils here https://github.com/dagger/dagger-for-github/pull/79/files will change the action over to using `dagger-cue`, but I take it that you see the goal to support both CUE versions of the Dagger cli `dagger` (i.e. from `v0.2.x` to `v0.2.36`) and `dagger-cue` (i.e. `v0.2.232`) and NOT support `dagger` `v0.3.x` which is not based on CUE.

This could be accomplished by using the`version` parameter with the ranges above and selecting `dagger` or `dagger-cue` as appropriate. The default for the next version of the GH action would be `dagger-cue` `v0.2.232`.

**Comment by marcosnils** [comment]
> but I take it that you see the goal to support both CUE versions of the Dagger cli `dagger` (i.e. from `v0.2.x` to `v0.2.36`) and `dagger-cue` (i.e. `v0.2.232`) and NOT support `dagger` `v0.3.x` which is not based on CUE.

IMO this would be a bit of a pain to maintain. I'd suggest releasing a new actions `major` version that only supports the new `dagger-cue` binary and is **NOT** compatible with the old one. That's the intention with the PR I initially started. @shykes shall I move forward with that one?

**Comment by fire** [comment]
I have stopped using dagger and will be unsubscribing from this thread, but I would suggest a new action for the new release.

**Comment by fire** [comment]
1. I spent like 2 days trying to onboard WSL2 install for docker on Windows
2. dagger github actions broke with no alternative other than rewriting from scratch. https://github.com/V-Sekai/v-sekai-game/blob/bd4c41bfd39a1825723041920169ef074d94a53e/.github/workflows/build-project.yml

**Comment by marcosnils** [comment]
> 1. I spent like 2 days trying to onboard a new developer using Windows on WSL2 install for docker on Windows (rancher desktop) and failed to install WSL2.

Sorry about this. Have you tried with podman on windows though? We have some users that can't pay for DD which are using podman with Dagger successfully. The good part is that they don't have to deal with all the WSL2 part.

> * dagger github actions broke with no alternative other than rewriting from scratch.

Sorry about that as well. Unfortunately, seems like you got caught in the middle of the `cue` to `SDK` pivot and we didn't do a good job to make that transition seamless. Having said that, some other users in Discord and github reported the same issue and we rapidly gave them a solution without having to do any extra work from their ends. Our dedication to our users and community is very valuable; if eventually you decide to try Dagger again, please let us know about things like this so we can address them ASAP.

> 3\. Our primary cicd system is in gocd. Using github actions and dagger was distracting.

Got it. Well.... hopefully we can get your team's attention sometime in the future. We'll be here in case there's anything we can do to help

**Comment by shykes** [comment]
> > but I take it that you see the goal to support both CUE versions of the Dagger cli `dagger` (i.e. from `v0.2.x` to `v0.2.36`) and `dagger-cue` (i.e. `v0.2.232`) and NOT support `dagger` `v0.3.x` which is not based on CUE.
> 
> IMO this would be a bit of a pain to maintain. I'd suggest releasing a new actions `major` version that only supports the new `dagger-cue` binary and is **NOT** compatible with the old one. That's the intention with the PR I initially started. @shykes shall I move forward with that one?

Resurrecting this. Yes let’s do it. Ideallwe take great care to have everyone use `v4` explicitly (in guides, templates etc) so that future releases (v5 & beyond) have more flexibility. v4 is certain to be our last cue-only release of this app: if we ever make another release it will be certain to a breaking change from v4, so might as well get prepared to keep that painless.

**Comment by mircubed** [comment]
Great, thanks @shykes ! @jpadams please let me know if you need any additional support for this. ccing @gerhard to keep him in the loop.
