### ISSUE TITLE
✨ Add parameter for different download location of the Dagger binaries

### ISSUE THREAD

**Issue by rajbos** [dagger/dagger-for-github#77]
### What are you trying to do?

We want to use this action on our GitHub Enterprise Server + self-hosted runners, and for security reasons we cannot let the runners download binaries from the internet. We can run security checks on them and store them inside of Artifactory.

For that purpose, we would like an extra parameter that we can pass in to download the Dagger binaries from. If you want, I can build it into a PR as well. That way we can override the default [location](https://github.com/dagger/dagger-for-github/blob/23fd2f48d13687b11cacd88aaf2082205e725bc3/src/dagger.ts#L11] if we need to (no param value == use default url).

### Why is this important to you?

Without this feature, our users cannot use Dagger with this action, and have to do everything themselves. We've had the request twice now, so they would really like to use it :-).

### How are you currently working around this?

We could create our own version of the action and download it from Artifactory ourselves, but I'd rather update functionality in the upstream repo and improve the world a little bit :-).

**Comment by jpadams** [comment]
@rajbos and @csalerno-asml sorry the lack of response on this issue. Going forward, we're going to base this action on Dagger v0.9.3+. I'll close this issue for now, but please re-open if you're still looking for a solution and we'll try to help. All the best!

**Comment by jpadams** [comment]
Sorry for the churn. Re-opening as this issue would still be relevant.

**Comment by jpadams** [comment]
for now, we're going to stick with the official binary location for this action. please raise another issue if this is still important 🙏
