### ISSUE TITLE
Rollback breakage caused by Dagger CLI 0.3 release

### ISSUE THREAD

**Issue by shykes** [dagger/dagger-for-github#80]
## Problem

We recently released a new Dagger CLI, version 0.3, which is a hard breaking change from 0.2. There is a migration path in preparation (using a new CLI called `dagger-cue` which is drop-in compatible with 0.2), that was meant to be rolled out soon.

But we accidentally broke users of the current github action *now*, without warning, by auto-updating this action to dagger 0.3. This should be immediately reversed regardless of future migration plans.

## Solution

Change the latest version of this action `@v3` to pin to `dagger` 0.2, instead of latest.

This should resolve the immediate issue for users of the Github Action, and allow us to finish planning a proper migration path.

Thank you @fredleger [for alerting us](https://github.com/dagger/dagger/pull/4069#issuecomment-1338967940) and we apologize for the poor experience!

**Comment by gerhard** [comment]
Hey @fredleger! Can you confirm that this fixes your issue?

**Comment by gerhard** [comment]
Sure thing! Thanks for the quick reply 🏎
